project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

website:
  title: "Brian Lookabaugh"
  image: "images/stickerv2.png"
  favicon: "images/stickerv2.png"
  description: "Brian Lookabaugh's Personal Website for Research and Blogs"
  navbar:
    logo: "images/sticker.png"
    left:
      - href: index.qmd
        text: Home
      - href: "resume/index.qmd"
        text: Resume
      - href: "research/index.qmd"
        text: Research
      - href: "blog/index.qmd"
        text: Blog
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/brian-lookabaugh-phd-372ab31a1/
      - icon: github
        href: https://github.com/Brian-Lookabaugh
      - icon: envelope
        href: mailto:brianlookabaughjr@gmail.com

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
    mainfont: Trebuchet MS
    fontsize: medium
