{
  "hash": "4684b96eedf555c384e5b579500e4459",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Be Wary of Regression-Based Causal Effects! (Or At Least Be Careful)...\"\ndate: 2025-05-26\ndescription: \"Regression is the backbone of almost all of causal inference. Yet, it is not perfect and it can have unique issues (some of which it won't even warn you about)! In this blog, we'll tackle what this hidden potential problem is, how to identify it, and how to respond to it.\"\nimage: \"figures/potential_outcomes.png\"\ntoc: true\nexecute:\n  warning: false\n  error: false\n  message: false\ntoc-location: \"left\"\ntoc-title: \"Contents\"\ncategories:\n  - causal inference\n  - regression\n---\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Load Libraries\npacman::p_load(\n  \"dplyr\", # Data Manipulation\n  \"ggplot2\", # Data Visualization\n  \"tidyr\", # Re-Shaping\n  \"scales\", # Scaling Visualizations\n  \"ggtext\", # Colored Text in Plots\n  \"gt\", # Nice Tables\n  install = FALSE\n)\n\n# Define a Custom Theme\nblog_theme <- function() {\n  theme_bw() +  \n    theme(\n      panel.grid.major = element_line(color = \"gray80\", size = 0.3),\n      panel.grid.minor = element_blank(),\n      panel.border = element_blank(),\n      plot.background = element_rect(fill = \"white\", color = NA),\n      plot.title = element_text(face = \"bold\", size = 16, margin = margin(t = 0, r = 0, b = 15, l = 0)),\n      axis.title.x = element_text(face = \"bold\", size = 14, margin = margin(t = 15, r = 0, b = 0, l = 0)),\n      axis.title.y = element_text(face = \"bold\", size = 14, margin = margin(t = 0, r = 15, b = 0, l = 0)),\n      strip.text = element_text(face = \"bold\"),\n      axis.text.x = element_text(face = \"bold\", size = 10), \n      axis.text.y = element_text(face = \"bold\", size = 10), \n      axis.ticks.x = element_blank(), \n      axis.ticks.y = element_blank(), \n      strip.background = element_rect(fill = \"grey80\", color = NA),\n      legend.title = element_text(face = \"bold\", size = 14),\n      legend.text = element_text(face = \"bold\", size = 10, color = \"grey25\"),\n    )\n}\n\n# Establish a Custom Color Scheme\ncolors <- c(\n  \"1\" = \"#133a29\",\n  \"2\" = \"#ab3d29\",\n  \"3\" = \"#f9ba6d\",\n  \"4\" = \"#314318\",\n  \"5\" = \"#63221f\"\n)\n```\n:::\n\n\n\nRegression is used reflexively in statistics, really regardless of what you're trying to do. Clearly, the tool has earned its place and I am not targeting it. I use regression all of the time and will use it probably for as long as I live. However, in this blog, I am going to demonstrate what many others have already documented thoroughly. \n\nPrimarily, that researchers should be aware of their data and aware of what estimates regression can produce even if the data used to estimate a regression model violate key assumptions for making causal inferences. For this problem in particular, output from really any statistical package/software will not tell you \"THIS IS A PROBLEM\" when you, in fact, have run into this specific problem. Instead, the burden is on us as the researcher to catch the problem (if the problem exists). \n\nBefore getting to the problem itself, it is useful to return to the potential outcomes framework (POF) for making causal inferences. After reviewing the POF, the tricky thing about regression to be on the lookout for should be more apparent.\n\n# Refresher on Potential Outcomes\n\nThe POF is a way of conceptualizing and formalizing causality and causal effects. The basic idea is that we can identify a causal effect by looking a unit who is exposed or not exposed to some exposure of interest and compare their outcome to the exact same unit whose exposure status is different. By doing so, we isolate the effect of the exposure of interest and so we don't have to worry about bias resulting from other things that affect the exposure and outcome of interest.\n\nThe fundamental problem of causal inference is that observing (in the case of a binary exposure, for example) *both* potential outcomes is impossible. You either received the exposure or you didn't. We need both ingredients to know the causal effect ($Y_{X_1} - Y_{X_0}$) but we only ever observe one. \n\nThankfully, absent a time machine, clever designs and statistical methods allow us to make inferences about *average* causal effects rather than more precise *individual*-level causal effects. If we had access to individual-level causal effects, we could also make *average* inferences by taking the average of the exposed and control outcomes and then take the difference. Below is a plot that shows simulated potential outcomes for 100 units who are randomly assigned to exposure/control. Also, note that I got this plot idea from [Dr. Julia Rohrer](https://www.the100.ci/author/julia/), so credit to her for this visualization.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Simulate Data\nset.seed(1234)\nn <- 100\n\n# Simulate Potential Outcomes and Random Treatment Assignment\nY_X_0 <- rnorm(n, 0, 0.05)\nY_X_1 <- 0.2 + rnorm(n, 0, 0.05)\nX <- rbinom(n, 1, 0.5)\nY <- ifelse(X == 1, Y_X_1, Y_X_0)\n\n# Create a Data Frame\nrandom_assignment <- data.frame(\n  id = 1:n,\n  X = X,\n  Y = Y,\n  Y_X_0 = Y_X_0,\n  Y_X_1 = Y_X_1\n)\n\n# Create a Long Data Set\nrandom_assignment_long <- random_assignment %>%\n  pivot_longer(cols = c(Y_X_0, Y_X_1),\n               names_to = \"potential_type\",\n               values_to = \"value\") %>%\n  mutate(\n    potential_type = recode(potential_type,\n                            Y_X_0 = \"Control\",\n                            Y_X_1 = \"Treated\")\n  )\n\n# Create a Wide Data Set for Connecting Lines\nrandom_assignment_wide <- random_assignment_long %>%\n  pivot_wider(names_from = potential_type, values_from = value)\n\n# Extract Density for Treated and Control for Overlay Plotting\nY_X_0_dens <- density(random_assignment$Y_X_0)\nY_X_1_dens <- density(random_assignment$Y_X_1)\n\ndensity <- bind_rows(\n  data.frame(x = Y_X_0_dens$x, y = rescale(Y_X_0_dens$y, to = c(1, 100)), type = \"Control\"),\n  data.frame(x = Y_X_1_dens$x, y = rescale(Y_X_1_dens$y, to = c(1, 100)), type = \"Treated\"))\n\n# Create the Dot Plots with Overlayed Distributions\nggplot() +\n  # Filled Density for Control\n  geom_area(data = density %>% filter(type == \"Control\"),\n            aes(x = x, y = y, fill = type),\n            alpha = 0.3) +\n  # Filled Density for Treated\n  geom_area(data = density %>% filter(type == \"Treated\"),\n            aes(x = x, y = y, fill = type),\n            alpha = 0.3) +\n  # Thicker Outline for Control Density\n  geom_line(data = density %>% filter(type == \"Control\"),\n            aes(x = x, y = y, color = type),\n            size = 1.5) +\n  # Thicker Outline for Treated Density\n  geom_line(data = density %>% filter(type == \"Treated\"),\n            aes(x = x, y = y, color = type),\n            size = 1.5) +\n  # Connect Lines Between Potential Outcomes Dots\n  geom_segment(data = random_assignment_wide,\n               aes(x = Control, xend = Treated,\n                   y = id, yend = id),\n               color = \"gray30\",\n               size = 0.5) +\n  # Dots for Potential Outcomes\n  geom_point(data = random_assignment_long,\n             aes(x = value, y = id, color = potential_type),\n             size = 2.5) +\n  scale_color_manual(values = c(\"Control\" = \"#133a29\", \"Treated\" = \"#63221f\")) +\n  scale_fill_manual(values = c(\"Control\" = \"#133a29\", \"Treated\" = \"#63221f\")) +\n  labs(\n    title = \"\",\n    subtitle = \"Difference between the average <b><span style='color:#63221f'>exposed outcome (0.205)</span></b> and the average <b><span style='color:#133a29'>control outcome (0.005)</span></b>\",\n    x = \"Potential Outcome Value\",\n    y = \"\",\n    color = \"Exposure Status\",\n    fill = \"Exposure Status\"\n  ) +\n  xlim(-0.2, 0.4) +\n  blog_theme() +\n  theme(\n    axis.text.y = element_blank(),\n    axis.ticks.y = element_blank(),\n    legend.position = \"none\",\n    plot.subtitle = ggtext::element_markdown(size = 11)\n  )\n```\n\n::: {.cell-output-display}\n![Distribution of Individual-Level Potential Outcomes](index_files/figure-html/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\n\nThis plot connects each unit's potential outcomes (via the gray line) between their known outcome when they are exposed (red) v. when they are not exposed (green). The average difference between the two 0.2 units which, if you look at the simulation code, is the exact causal effect that I specified it to be.\n\nBut, as I said before, we only ever know *one* of the potential outcomes. We will never know both, but we are still interested in estimating the average causal effect. How do we do this? Well, because I randomized which units were *actually* exposed to the exposure ($X$), this allows us to estimate the *average* causal effect free from bias (check out [this blog post](https://brian-lookabaugh.github.io/website-brianlookabaugh/blog/2024/causal-inference-simulation/#the-power-of-randomization) if you want to know how that process works). \n\nAnd because $X$ is randomized, I can simply regress the observed outcomes on the randomized exposure and I should also get 0.2 (the average causal effect we know to be true because I simulated data explicitly ordering it to be as such!)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(Y ~ X, data = random_assignment)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Y ~ X, data = random_assignment)\n\nCoefficients:\n(Intercept)            X  \n  -0.002366     0.199678  \n```\n\n\n:::\n:::\n\n\n\nYup, and that's what we see! 0.199678 is pretty close to 0.2! But, what happens when $X$ is not randomly assigned? Here, we run into a challenging problem. Many researchers address this by operating under a causal identification strategy known as \"selection on observables\" (see more about this [here](https://brian-lookabaugh.github.io/website-brianlookabaugh/blog/2024/causal-inference-simulation/#when-experiments-fall-short)) where we statistically adjust for each variable that influences both $X$ and $Y$. But that itself introduces some problems that we will get into for the next section.\n\nAnd yes, these problems are the ones that warrant the caution about regression that this blog is titled after.\n\n# Positivity/Common Support\n\nA key assumption for causal inference is the positivity assumption (also known as common support). The key point is that, within each combination of covariates (aka stratum), the probability of any unit being exposed to the exposure is non-zero. That is, however the data is separated (i.e. $Z_1$ = 1 & $Z_2$ = 1 or $Z_1$ = 1 & $Z_2$ = 0, etc.), there should always be a possibility for exposure.\n\nThe following plot demonstrates this by looking at an exposure-outcome relationship confounded by two binary confounders. It plots the percent of observations that, within each covariate combination, are exposed v. control.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Simulate Data\nset.seed(1234)\nn <- 10000\n\n# Simulate Potential Outcomes and Random Treatment Assignment\nZ1 <- rbinom(n, 1, 0.3)\nZ2 <- rbinom(n, 1, 0.7)\nX <- rbinom(n, 1, prob = plogis(0.5 + 0.3 * Z1 + -0.6 * Z2))\nY_X_0 <- 0 + 0.4 * Z1 + 0.7 * Z2 + rnorm(n, 0, 0.25)\nY_X_1 <- 0.2 + 0.4 * Z1 + 0.7 * Z2 + rnorm(n, 0, 0.25)\nY <- Y_X_1 * X + Y_X_0 * (1 - X) \n\n# Create a Data Frame\nconfounded <- data.frame(\n  id = 1:n,\n  X = X,\n  Y = Y,\n  Y_X_0 = Y_X_0,\n  Y_X_1 = Y_X_1,\n  Z1 = Z1,\n  Z2 = Z2\n)\n\n# Create a Grouped Bar Plot to Show Exposure/Control Distribution per Covariate Combination\nconfounded %>%\n  mutate(group = paste0(\"Z1 = \", Z1, \", Z2 = \", Z2)) %>%\n  count(group, X) %>%\n  group_by(group) %>%\n  mutate(percentage = n / sum(n) * 100,\n         status = ifelse(X == 1, \"Exposure\", \"Control\")) %>%\n  ungroup() %>%\n  ggplot(aes(x = group, y = percentage, fill = status)) +\n  geom_bar(stat = \"identity\", position = \"dodge\", width = 0.7, color = \"black\", size = 0.75) +\n  geom_text(aes(label = paste0(round(percentage, 1), \"%\")),\n            position = position_dodge(width = 0.7),\n            vjust = -0.5, size = 3.5, fontface = \"bold\") +\n  scale_fill_manual(values = c(\"Control\" = \"#133a29\", \"Exposure\" = \"#63221f\")) +\n  scale_y_continuous(labels = function(x) paste0(x, \"%\")) +\n  labs(\n    title = \"\",\n    x = \"Covariate Combinations\",\n    y = \"Percentage of Observations\",\n    fill = \"\"\n  ) +\n  blog_theme()\n```\n\n::: {.cell-output-display}\n![Exposure/Control Distribution Across Covariate Combinations](index_files/figure-html/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n\nEven though, within each stratum, the distribution of the exposure is not even, the probability is *all* non-zero. To  put this in other terms, we observe both exposed and control for units where $Z_1$ = 0 & where $Z_2$ = 0, we observe both exposed and control for units where $Z_1$ = 0 & where $Z_2$ = 1, etc. Within each stratum, we are able to observe counterfactuals for each exposure condition (exposed v. control) and are thus able to reconstruct the potential outcomes.\n\nThis situation is good, but it is also incredibly naive (for one, there are only two binary confounders... very unlikely in real life.) We also are lucky because we happen to not struggle with a positivity violation here. But what might such a violation look like?\n\n# Violating Posivity with Regression is Easy!\n\nTo dive into this question, I am going to borrow from the same data, but I am going to make it so that the stratum $Z_1$ = 1 & $Z_2$ = 1 are *never* exposed.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlack_overlap <- confounded %>%\n  mutate(X = ifelse(Z1 == 1 & Z2 == 1, 0, X))\n```\n:::\n\n\n\nAdmittedly, the way I am handling a lack of overlap is a bit heavy handed. As you can see in the code, I am simulating a data set where this is full treatment overlap in the covariates, but I am artificially creating a new data set from the simulated one where one combination of covariates results in the exposure always being 0. However, there are several ways that this could happen with real data.\n\nFor example, perhaps simply due to sampling error, you manage to get a combination of covariates where there is only one treatment status. Or, perhaps we naturally observe in the world that a specific combination of covariates happens to always lead to one treatment status. For example, assume that the exposure of interest in a certain study is a binary indicator of civil conflict. Imagine that I control for GDP per capita and the presence of a UN peacekeeping operation. I imagine that it is very unlikely to ever observe an instance where a rich country that does not have a UN peacekeeping operation is *also* experiencing a civil war. This probably sounds a bit niche, but a lack of overlap might not be incredibly systematic. It truly might only exist in one stratum of your data.\n\nBut, all that being said, the following bar plot helps visualize why a lack of overlap is an issue.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Create a Grouped Bar Plot to Show Exposure/Control Distribution per Covariate Combination\nlack_overlap %>%\n  mutate(group = paste0(\"Z1 = \", Z1, \", Z2 = \", Z2)) %>%\n  count(group, X) %>%\n  mutate(status = ifelse(X == 1, \"Exposure\", \"Control\")) %>%\n  select(-X) %>%\n  complete(group, status, fill = list(n = 0)) %>%\n  group_by(group) %>%\n  mutate(percentage = n / sum(n) * 100) %>%\n  ungroup() %>%\n  ggplot(aes(x = group, y = percentage, fill = status)) +\n  geom_bar(stat = \"identity\", position = position_dodge(width = 0.7),\n           width = 0.7, color = \"black\", size = 0.75) +\n  geom_text(aes(label = paste0(round(percentage, 1), \"%\")),\n            position = position_dodge(width = 0.7),\n            vjust = -0.5, size = 3.5, fontface = \"bold\") +\n  scale_fill_manual(values = c(\"Control\" = \"#133a29\", \"Exposure\" = \"#63221f\")) +\n  scale_y_continuous(labels = function(x) paste0(x, \"%\")) +\n  labs(\n    title = \"\",\n    x = \"Covariate Combinations\",\n    y = \"Percentage of Observations\",\n    fill = \"\"\n  ) +\n  blog_theme()\n```\n\n::: {.cell-output-display}\n![Exposure/Control Distribution Across Covariate Combinations with Positivity Violated](index_files/figure-html/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n\n\nSo, in the $Z_1$ = 1, $Z_2$ = 1 stratum, all units are control observations... What consequence might that have for estimating the causal effect of the exposure ($X$)? Well, recall that the true causal effect is 0.2. And, we can demonstrate that we can estimate this causal effect even with confounders through the following regression:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(Y ~ X + Z1 + Z2, data = confounded)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Y ~ X + Z1 + Z2, data = confounded)\n\nCoefficients:\n(Intercept)            X           Z1           Z2  \n  -0.003636     0.201851     0.398327     0.700668  \n```\n\n\n:::\n:::\n\n\n\nSo, that being said, how does the coefficient for $X$ change using the data where the positivity assumption is violated? Let's check that out!\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlack_overlap_mod <- lm(Y ~ X + Z1 + Z2, data = lack_overlap)\n\nlack_overlap_mod\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Y ~ X + Z1 + Z2, data = lack_overlap)\n\nCoefficients:\n(Intercept)            X           Z1           Z2  \n   -0.01668      0.18888      0.47062      0.72909  \n```\n\n\n:::\n:::\n\n\n\nAs we can see, we have found some bias even though all the confounders are accounted for. So clearly, violating the positivity assumption, in some way, matters for estimating unbiased causal effects. But... how exactly does that work? Well, the bias can be explained, in part, by what is happening on a more micro-level. \n\nReporting average marginal effects (AMEs) is a popular strategy for reporting predicted causal effects from regression output. I bring this up because how AMEs are calculated can help demonstrate where the bias of positivity violations comes from.\n\nThe basic idea of AMEs is this:\n\n1) Estimate a model regressing the outcome on the exposure of interest + all confounders\n\n2) Use the model to predict the outcome by \"plugging in\" the exposure and confounder values. For example, if a unit was exposed to treatment and had a $Z1$ and $Z2$ value of 0, than the marginal effect for that unit, using our biased regression model, would be calculated using: $Y = -0.017 + 0.189 (1) + 0.471 (0) + 0.729 (0)$. So, for this unit, the predicted outcome when exposed to the treatment would be 0.172\n\n3) Use the model to predict the potential outcome by changing the exposure value in the regression equation. Again, using our hypothetical example, we are going to \"plug in\" all the same values but just change the exposure value to control, which would look like: $Y = -0.017 + 0.189 (0) + 0.471 (0) + 0.729 (0)$. So, for this unit, the predicted outcome when *not* exposed to the treatment would be -0.017.\n\n4) Take the difference between the observed predicted outcome and the counterfactual predicted outcome: 0.172 - -0.017 = 0.189 (this is our coefficient!)\n\n5) Do this for every unit and take the average difference of the differences. That is our average marginal effect.\n\nSo how do AMEs help explain why our coefficient becomes biased when positivity is violated? Well, let's return to our pesky stratum of $Z_1$ = 1 and $Z_2$ = 1. Remember, we *know* that all units in this stratum are controls. So we can predict the outcome for these units easily by: $Y = -0.017 + 0.189 (0) + 0.471 (1) + 0.729 (1)$ which sums to 1.183. Easy enough, but what about the next step. We want to know the counterfactual and that formula would be: $Y = -0.017 + 0.189 (1) + 0.471 (1) + 0.729 (1)$.\n\nUh-oh... we already know that, within the $Z_1$ = 1 and $Z_2$ = 1 stratum, *no* units are exposed... so how can we know what the impact of exposure would be? Well, our model will gladly give us a predicted outcome, but that outcome is not generated from any *real* data points within that stratum. In other words, it is made up! Or, in fancier terms, regression is *extrapolating beyond the support of the data*. It is making a guess without any data points. That's kind of a problem! And we see the fruits of this problem bear out in a biased coefficient.\n\nNow, because I know what each potential outcome *actually is* (because I simulated it), we can do something really interesting where we estimate the predicted counterfactual outcome (when units in this stratum are exposed) and compare it to the *true* counterfactual outcome. So, that's what the following table reports. \n\nFrom the data set of 10,000 units, I randomly sampled observations from the $Z_1$ = 1 and $Z_2$ = 1 stratum and compared their predicted counterfactual outcome to the true counterfactual outcome. In an ideal world, our predicted counterfactual outcome is equivalent to the true counterfactual outcome.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Estimate Potential Outcomes for Units with No Covariate Overlap\nsampled <- lack_overlap %>%\n  filter(Z1 == 1, Z2 == 1) %>%\n  filter(Y != Y_X_1) %>%\n  sample_n(5)\n\nsampled_counterfactual <- sampled %>%\n  mutate(X = 1)\n\nsampled_counterfactual <- sampled_counterfactual %>%\n  mutate(Y_pred = predict(lack_overlap_mod, newdata = sampled_counterfactual))\n\n# Present Select Predicted Results with a Table\nsampled_counterfactual %>%\n  mutate(bias = Y_X_1 - Y_pred) %>%\n  select(id, Y, Y_pred, Y_X_1, bias) %>%\n  gt() %>%\n  tab_header(title = \"Counterfactual Outcome Predictions\") %>%\n  cols_label(\n    id = \"Observation #\",\n    Y = \"Real Outcome\",\n    Y_pred = \"Predicted Counterfactual\",\n    Y_X_1 = \"True Counterfactual\",\n    bias = \"Bias\"\n  ) %>%\n  fmt_number(columns = c(Y, Y_pred, Y_X_1, bias), decimals = 3) %>%\n  cols_align(\n    align = \"center\",\n    columns = everything()\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hddxpndxna\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#hddxpndxna table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#hddxpndxna thead, #hddxpndxna tbody, #hddxpndxna tfoot, #hddxpndxna tr, #hddxpndxna td, #hddxpndxna th {\n  border-style: none;\n}\n\n#hddxpndxna p {\n  margin: 0;\n  padding: 0;\n}\n\n#hddxpndxna .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hddxpndxna .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#hddxpndxna .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hddxpndxna .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hddxpndxna .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hddxpndxna .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hddxpndxna .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hddxpndxna .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hddxpndxna .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hddxpndxna .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hddxpndxna .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hddxpndxna .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hddxpndxna .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#hddxpndxna .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#hddxpndxna .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hddxpndxna .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hddxpndxna .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hddxpndxna .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hddxpndxna .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hddxpndxna .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hddxpndxna .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hddxpndxna .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#hddxpndxna .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hddxpndxna .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hddxpndxna .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hddxpndxna .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hddxpndxna .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hddxpndxna .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hddxpndxna .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hddxpndxna .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hddxpndxna .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hddxpndxna .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hddxpndxna .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hddxpndxna .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hddxpndxna .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hddxpndxna .gt_left {\n  text-align: left;\n}\n\n#hddxpndxna .gt_center {\n  text-align: center;\n}\n\n#hddxpndxna .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hddxpndxna .gt_font_normal {\n  font-weight: normal;\n}\n\n#hddxpndxna .gt_font_bold {\n  font-weight: bold;\n}\n\n#hddxpndxna .gt_font_italic {\n  font-style: italic;\n}\n\n#hddxpndxna .gt_super {\n  font-size: 65%;\n}\n\n#hddxpndxna .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#hddxpndxna .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hddxpndxna .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hddxpndxna .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hddxpndxna .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hddxpndxna .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hddxpndxna .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#hddxpndxna .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#hddxpndxna div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"5\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>Counterfactual Outcome Predictions</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"id\">Observation #</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Y\">Real Outcome</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Y_pred\">Predicted Counterfactual</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Y_X_1\">True Counterfactual</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"bias\">Bias</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"id\" class=\"gt_row gt_center\">8171</td>\n<td headers=\"Y\" class=\"gt_row gt_center\">0.961</td>\n<td headers=\"Y_pred\" class=\"gt_row gt_center\">1.372</td>\n<td headers=\"Y_X_1\" class=\"gt_row gt_center\">1.729</td>\n<td headers=\"bias\" class=\"gt_row gt_center\">0.357</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_center\">7383</td>\n<td headers=\"Y\" class=\"gt_row gt_center\">1.144</td>\n<td headers=\"Y_pred\" class=\"gt_row gt_center\">1.372</td>\n<td headers=\"Y_X_1\" class=\"gt_row gt_center\">1.103</td>\n<td headers=\"bias\" class=\"gt_row gt_center\">−0.269</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_center\">2682</td>\n<td headers=\"Y\" class=\"gt_row gt_center\">1.213</td>\n<td headers=\"Y_pred\" class=\"gt_row gt_center\">1.372</td>\n<td headers=\"Y_X_1\" class=\"gt_row gt_center\">1.291</td>\n<td headers=\"bias\" class=\"gt_row gt_center\">−0.081</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_center\">8621</td>\n<td headers=\"Y\" class=\"gt_row gt_center\">0.991</td>\n<td headers=\"Y_pred\" class=\"gt_row gt_center\">1.372</td>\n<td headers=\"Y_X_1\" class=\"gt_row gt_center\">0.995</td>\n<td headers=\"bias\" class=\"gt_row gt_center\">−0.377</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_center\">7492</td>\n<td headers=\"Y\" class=\"gt_row gt_center\">0.556</td>\n<td headers=\"Y_pred\" class=\"gt_row gt_center\">1.372</td>\n<td headers=\"Y_X_1\" class=\"gt_row gt_center\">1.129</td>\n<td headers=\"bias\" class=\"gt_row gt_center\">−0.243</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\nAnd, unsurprisingly, we see that there is bias... No shocker there.\n\nSo, with all of this being said, what are you supposed to do if positivity is violated? Or, for the keen readers out there, how are you supposed to check for positivity? Most of us are working with adjustment sets that have continuous, ordinal, and count confounders in addition to binary confounders. And we certainly have a lot more than two... How are you supposed to check for positivity under these conditions?\n\n# Checking for Posivity or Considering Other Approaches\n\nIn other words, we might say that realistic situations involve adjustment sets that are multi-dimensional. If we just had two binary confounders, we can check for overlap with a simple 2x2 square. But adding more confounders and more different types of confounders makes such a simplistic approach impossible.\n\nOne solution is to estimate a propensity score and check for overlap between exposed and control units. For those not familiar, the propensity score is simply the predicted probability of a unit receiving their level of exposure conditional on the confounders. You can do this with something as simple as a logit model. In the context of our simple two-confounders example, you could get propensity scores by:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nps_score_model <- glm(X ~ Z1 + Z2, data = confounded, family = binomial(link = \"logit\"))\n\nconfounded$ps <- predict(ps_score_model, type = \"response\")\n```\n:::\n\n\n\nThe propensity score is useful because it collapses all of the information from $k$ confounders and summarizes what we need to know (the probability of receiving treatment) into one metric. Once we have obtained propensity scores, we can compare their distribution between the exposed and control units. Take, for example, a plot I made for another blog post below:\n\n![Example Using Propensity Scores to Assess Positivity](C:/Users/brian/Documents/website-brianlookabaugh/blog/2025/extrapolation/figures/att_plot.png)\nThis plot shows us that, for treated units, the probability of receiving treatment ranges from about 20% to about 80% while the distribution for control units ranges from 0% to about 80%. What do we learn from this? Well, it shows us that, for the analysis of *treated* units, there are potentially comparable control units that can allow us to estimate the potential outcomes for the treated units. In other terms, for each propensity score that a treated unit may have, there is at least one other *control* unit that has the same propensity score.\n\nSo, propensity scores are one potential for evaluating positivity, but... isn't there still a problem here? What about the control units whose propensity scores range from 0% to 19%? According to the propensity scores, we can't estimate potential outcomes for these units. And, in this case, that would be correct, but it doesn't mean that your study would be doomed. One solution to violations of positivity is simply to *answer another question*.\n\nSure, in this case, you wouldn't be able to estimate the potential outcomes for *every* unit in your study, but you *can* estimate the potential outcomes for *every treated unit*. This gets to the concept of an *estimand* or a targeted theoretical value that you are trying to *estimate*. The estimand is the ideal that we are searching for out in the wild and the estimate is our best attempt to locate it. Not every estimand requires as strict positivity assumptions. \n\nSure, if you want to estimate potential outcomes for *every* unit in your study, then you would need complete overlap. This is what is required to estimate the average treatment effect (ATE) that is often estimated in experimental designs where the treated and control units have the exact same probability of receiving treatment. But, as is the case from this example, the ATE may not always be a feasible estimand (and sometimes, it may not even be desired). Instead, for our purposes with this hypothetical example, we could instead estimate the average treatment effect *for the treated* (the *ATT*), which is exactly what it sounds like - the average effect of the treatment *for the treated units*. We make that caveat because, in this context, we would be unable to estimate the average effect of the treatment for the control units (this is known as the ATU or ATC).\n\nSituated within the context of the positivity assumption, we violate positivity in our context dependent on the estimand we are targeting. For this example, we would violate positvity is we tried to estimate the ATE or ATU, but we would *not* violate positivity if we shot for the ATT. However, remember that we still should pay attention to specific stratum in our data that might be sneakily flying under the radar as well (such as the $Z_1$ = 1 and $Z_2$ = 1 example). It is still possible that such nuances could go undetected with a \"dimensionality reduction\" statistic like the propensity score. As always with anything causal inference related, know your data well and really dig into it looking for stuff exactly like this before diving into analysis. As regression demonstrates, not all methods will let you know when you're violating a key assumption.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}